module.exports = {
  USER_ROLES: { USER: 'user', SELLER: 'seller', ADMIN: 'admin' },
  USER_STATUS: { ACTIVE: 'active', SUSPENDED: 'suspended', BANNED: 'banned' },
  PRODUCT_CONDITIONS: { NEW: 'new', LIKE_NEW: 'like_new', GOOD: 'good', FAIR: 'fair', FOR_PARTS: 'for_parts' },
  PRODUCT_STATUS: { DRAFT: 'draft', ACTIVE: 'active', SOLD: 'sold', ARCHIVED: 'archived', FLAGGED: 'flagged', BANNED: 'banned' },
  ORDER_STATUS: {
    PENDING_PAYMENT: 'pending_payment', PAYMENT_VERIFIED: 'payment_verified', PROCESSING: 'processing',
    SHIPPED: 'shipped', DELIVERED: 'delivered', COMPLETED: 'completed',
    CANCELLED: 'cancelled', REFUNDED: 'refunded', DISPUTED: 'disputed',
  },
  ESCROW_STATUS: { PENDING: 'pending', HELD: 'held', RELEASED: 'released', REFUNDED: 'refunded', DISPUTED: 'disputed' },
  PAYMENT_METHODS: { TELEBIRR: 'telebirr', CASH_ON_DELIVERY: 'cash_on_delivery', BANK_TRANSFER: 'bank_transfer' },
  DELIVERY_METHODS: { PICKUP: 'pickup', DELIVERY: 'delivery' },
  ETHIOPIAN_CITIES: ['Addis Ababa', 'Dire Dawa', 'Mekelle', 'Gondar', 'Bahir Dar', 'Hawassa', 'Adama', 'Jimma', 'Dessie', 'Harar'],
  ADDIS_ABABA_SUBCITIES: ['Bole', 'Kazanchis', 'Piassa', 'Merkato', 'Kirkos', 'Yeka', 'Gulele', 'Kolfe Keranio', 'Lideta', 'Nifas Silk-Lafto', 'Arada', 'Addis Ketema', 'Akaki Kality'],
  CATEGORIES: [
    { name: 'Electronics', subcategories: ['Phones', 'Laptops', 'Tablets', 'Cameras', 'Audio', 'Gaming'] },
    { name: 'Furniture', subcategories: ['Sofas', 'Beds', 'Tables', 'Chairs', 'Cabinets', 'Office Furniture'] },
    { name: 'Clothing', subcategories: ['Men', 'Women', 'Kids', 'Shoes', 'Accessories', 'Traditional'] },
    { name: 'Books', subcategories: ['Textbooks', 'Fiction', 'Children', 'Academic', 'Religious'] },
    { name: 'Home Appliances', subcategories: ['Refrigerators', 'Washing Machines', 'Microwaves', 'Air Conditioners'] },
    { name: 'Vehicles', subcategories: ['Cars', 'Motorcycles', 'Bicycles', 'Spare Parts'] },
    { name: 'Sports & Outdoors', subcategories: ['Fitness', 'Camping', 'Team Sports', 'Cycling'] },
    { name: 'Baby & Kids', subcategories: ['Toys', 'Strollers', 'Clothing', 'Furniture'] },
  ],
  TRANSACTION_FEE_PERCENT: 5,
  MIN_FEE: 10,
  MAX_FEE: 500,
  ESCROW_RELEASE_DAYS: 2,
  LISTING_EXPIRY_DAYS: 60,
};
